### ISSUE TITLE
Empty output with serialized database 

### ISSUE THREAD

**Issue by ericolo** [jolespin/pykofamsearch#5]
Hi ! 

I'm trying to use the serialized database but I can't make it work, the output file is empty...

I downloaded the official KOfam database and made it into a serialized database just as in the example

(The `-d` option without the non-serialized database works fine, I want to use the serialized one to speed things up)

Thanks in advance !

**Comment by jolespin** [comment]
Can you post the commands you used? It'll give me a better idea of where to start in the debug.

**Comment by ericolo** [comment]
Yes, here is what I did:

I downloaded and created the database just as explained in your README, then to serialize it I did:

`serialize_kofam_models.py -d $HOME/Annotate/KOFAM/ -k $HOME/Annotate/KOFAM/ko_list -b $HOME/Annotate/KOFAM/kofam_june2024.pkl.gz`

And then:

`pykofamsearch.py -i 638154511.faa  -o output.tsv -b $HOME/Annotate/KOFAM/kofam_june2024.pkl.gz -p=10 -t 0.5`

But `output.tsv` is empty, if I do it on the non-serialized database it works and the file is not empty

**Comment by jolespin** [comment]
Hmm...I just ran it without any issues when I didn't use the thresholding argument (stable version on pypi): 

```
(kofamscan_env) Joshs-MBP:KOfam jolespin$ serialize_kofam_models.py -d profiles/ -k ko_list -b test.pkl
Loading KOfam HMMs: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26598/26598 [01:01<00:00, 431.51it/s]
------------------------
Number of missing KOfams: 436
------------------------

(kofamscan_env) Joshs-MBP:KOfam jolespin$ ls -lh
total 9492768
-rw-r--r--@     1 jolespin  staff   478M Apr 25 17:06 database.enzymes.pkl.gz
-rw-r--r--@     1 jolespin  staff   1.2G Apr 25 17:30 database.pkl.gz
-rw-r--r--@     1 jolespin  staff   398K May  3 14:58 kegg_orthologs.thresholds.enzymes.tsv.gz
-rw-r--r--@     1 jolespin  staff   887K Apr 25 17:11 kegg_orthologs.thresholds.tsv.gz
-rw-r--r--      1 jolespin  staff   2.6M Apr  9 17:16 ko_list
drwxrwxr-x  26166 jolespin  staff   818K Mar 25 01:46 profiles
-rw-r--r--@     1 jolespin  staff   2.8G Jul  8 10:54 test.pkl

(kofamscan_env) Joshs-MBP:KOfam jolespin$ pykofamsearch.py -i /Users/jolespin/Cloud/Informatics/Oath/Analysis/CGWGLL031318/genomes/spades-full_assembly/1-1_1.faa -o output.tsv -b test.pkl -p=10 -t 0.5
usage: pykofamsearch.py -i <proteins.fasta> -o <output.tsv> -d
pykofamsearch.py: error: unrecognized arguments: -t 0.5
(kofamscan_env) Joshs-MBP:KOfam jolespin$ pykofamsearch.py -i /Users/jolespin/Cloud/Informatics/Oath/Analysis/CGWGLL031318/genomes/spades-full_assembly/1-1_1.faa -o output.tsv -b test.pkl -p=10
Loading serialized KOFAM database
Performing HMMSearch: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26162/26162 [04:29<00:00, 97.19it/s]

(kofamscan_env) Joshs-MBP:KOfam jolespin$ head -n 5 output.tsv
id_protein	id_ko	threshold	score	e-value	definition
1-1_1__NODE_16_length_141593_cov_101.845367_110	K00003	284.43	596.797	1.86682e-179	homoserine dehydrogenase [EC:1.1.1.3]
1-1_1__NODE_9_length_243110_cov_79.307876_133	K00010	272.37	353.617	5.39314e-106	myo-inositol 2-dehydrogenase / D-chiro-inositol 1-dehydrogenase [EC:1.1.1.18 1.1.1.369]
1-1_1__NODE_10_length_242105_cov_112.044185_7	K00010	272.37	334.534	3.39116e-100	myo-inositol 2-dehydrogenase / D-chiro-inositol 1-dehydrogenase [EC:1.1.1.18 1.1.1.369]
1-1_1__NODE_23_length_93543_cov_118.734577_45	K00012	377.73	594.770	1.02109e-178	UDPglucose 6-dehydrogenase [EC:1.1.1.22]
```

Can you try without the thresholding argument? @apcamargo any insight on this?

**Comment by ericolo** [comment]
Without the threshold argument it doesn't work either, the version I have is a fix from @apcamargo
I tried re-installing the stable version from pypi, and I get the this (then @apcamargo fixed it internally) : 

``` 
(base) [eolondela@ln008 testing_kofams]$ pykofamsearch.py -i 638154511.faa  -o output.tsv -b $MY_SCRATCH/DB_and_tools/Annotate/KOFAM/kofam_june2024.pkl.gz -p=10 
Loading serialized KOFAM database
Performing HMMSearch: 0it [00:00, ?it/s]
------------------------
Traceback (most recent call last):
  File "/clusterfs/jgi/groups/science/homes/eolondela/.micromamba/bin/pykofamsearch.py", line 241, in <module>
    main(sys.argv[1:])
  File "/clusterfs/jgi/groups/science/homes/eolondela/.micromamba/bin/pykofamsearch.py", line 232, in main
    print("Number of missing KOfams: {}".format(len(missing_kos)), file=sys.stderr)
UnboundLocalError: local variable 'missing_kos' referenced before assignment
```

Is that the right version ?

``` 
(base) [eolondela@ln008 testing_kofams]$ pykofamsearch.py --help
usage: pykofamsearch.py -i <proteins.fasta> -o <output.tsv> -d 

    Running: pykofamsearch.py v2024.6.8 via Python v3.9.18 | /clusterfs/jgi/groups/science/homes/eolondela/.micromamba/bin/python
 ```

**Comment by jolespin** [comment]
Oh yea the missing_kos error.  Ok I'm retrying w/ the dev build.  I'll try to pinpoint the error.

**Comment by jolespin** [comment]
Can you try redownloading your database files and building again? It's working for me with the developmental build on GitHub.  If you want to use that one, just do `pip install git+https://github.com/jolespin/pykofamsearch`

```
(kofamscan_env) Joshs-MBP:KOfam jolespin$ serialize_kofam_models.py -d profiles/ -k ko_list -b test.pkl
Loading KOfam HMMs: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26598/26598 [00:59<00:00, 444.35it/s]
------------------------
Number of missing KOfams: 436
------------------------

(kofamscan_env) Joshs-MBP:KOfam jolespin$ pykofamsearch.py --help | grep "v2024"
    Running: pykofamsearch.py v2024.7.8 via Python v3.10.14 | /Users/jolespin/miniconda3/envs/kofamscan_env/bin/python3.10

(kofamscan_env) Joshs-MBP:KOfam jolespin$ pykofamsearch.py -i /Users/jolespin/Cloud/Informatics/Oath/Analysis/CGWGLL031318/genomes/spades-full_assembly/1-1_1.faa -o output.tsv -b test.pkl -p=10
Loading serialized KOFAM database
Performing HMMSearch: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26162/26162 [04:23<00:00, 99.28it/s]
------------------------
Number of missing KOfams: 436
------------------------
(kofamscan_env) Joshs-MBP:KOfam jolespin$ tail -n 5 output.tsv
1-1_1__NODE_27_length_59718_cov_75.590433_39	K27097	59.47	73.835	6.14591e-21	ESX-1-secreted protein regulator
1-1_1__NODE_27_length_59718_cov_75.590433_15	K27097	59.47	69.887	9.92853e-20	ESX-1-secreted protein regulator
1-1_1__NODE_8_length_311684_cov_84.355788_195	K27097	59.47	62.688	1.58588e-17	ESX-1-secreted protein regulator
1-1_1__NODE_5_length_397441_cov_92.766096_283	K27109	126.27	178.157	2.59094e-53	cytochrome c oxidase subunit IV [EC:7.1.1.9]
1-1_1__NODE_17_length_135448_cov_98.063079_82	K27194	331.8	558.061	2.60604e-168	MMP endo-(1,4)-3-O-methyl-alpha-D-mannosidase [EC:3.2.1.221]

(kofamscan_env) Joshs-MBP:KOfam jolespin$ pykofamsearch.py -i /Users/jolespin/Cloud/Informatics/Oath/Analysis/CGWGLL031318/genomes/spades-full_assembly/1-1_1.faa -o output_t-0.5.tsv -b test.pkl -p=10 -t 0.5
Loading serialized KOFAM database
Performing HMMSearch: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26162/26162 [04:23<00:00, 99.46it/s]
------------------------
Number of missing KOfams: 436
------------------------
(kofamscan_env) Joshs-MBP:KOfam jolespin$ head -n 5 output_t-0.5.tsv
id_protein	id_ko	threshold	score	e-value	definition
1-1_1__NODE_7_length_336536_cov_82.177085_72	K00001	165.685	293.576	1.57306e-87	alcohol dehydrogenase [EC:1.1.1.1]
1-1_1__NODE_6_length_354970_cov_64.409836_159	K00001	82.8425	290.068	1.83105e-86	alcohol dehydrogenase [EC:1.1.1.1]
1-1_1__NODE_17_length_135448_cov_98.063079_71	K00001	41.42125	277.619	1.10340e-82	alcohol dehydrogenase [EC:1.1.1.1]
1-1_1__NODE_5_length_397441_cov_92.766096_4	K00001	20.710625	200.947	1.89200e-59	alcohol dehydrogenase [EC:1.1.1.1]
```

**Comment by ericolo** [comment]
Hmm I re-installed it then re-downloaded the DB, but it still didn't work with the serialized version, but it did with the normal DB, here are my commands and the output in case you see something: 

```
(base) [eolondela@ln008 DB_and_tools]$ DATABASE_DIRECTORY=/clusterfs/jgi/scratch/science/mds/eolondela/DB_and_tools
(base) [eolondela@ln008 DB_and_tools]$ 
(base) [eolondela@ln008 DB_and_tools]$ 
(base) [eolondela@ln008 DB_and_tools]$ mkdir -p ${DATABASE_DIRECTORY}/Annotate/KOFAM/
(base) [eolondela@ln008 DB_and_tools]$ 
(base) [eolondela@ln008 DB_and_tools]$ 
(base) [eolondela@ln008 DB_and_tools]$ wget -v -O - ftp://ftp.genome.jp/pub/db/kofam/ko_list.gz | gzip -d > ${DATABASE_DIRECTORY}/Annotate/KOFAM/ko_list
--2024-07-08 14:48:03--  ftp://ftp.genome.jp/pub/db/kofam/ko_list.gz
           => ‘-’
Resolving ftp.genome.jp (ftp.genome.jp)... 133.103.200.25
Connecting to ftp.genome.jp (ftp.genome.jp)|133.103.200.25|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/db/kofam ... done.
==> SIZE ko_list.gz ... 858206
==> PASV ... done.    ==> RETR ko_list.gz ... done.
Length: 858206 (838K) (unauthoritative)

ko_list.gz               100%[=================================>] 838.09K  1.04MB/s    in 0.8s    

2024-07-08 14:48:06 (1.04 MB/s) - written to stdout [858206]

(base) [eolondela@ln008 DB_and_tools]$ wget -v -c ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz -O - |  tar -xz
--2024-07-08 14:48:12--  ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz
           => ‘-’
Resolving ftp.genome.jp (ftp.genome.jp)... 133.103.200.25
Connecting to ftp.genome.jp (ftp.genome.jp)|133.103.200.25|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/db/kofam ... done.
==> SIZE profiles.tar.gz ... 1476206212
==> PASV ... done.    ==> RETR profiles.tar.gz ... done.
Length: 1476206212 (1.4G) (unauthoritative)

profiles.tar.gz          100%[=================================>]   1.37G  1.86MB/s    in 6m 22s  

2024-07-08 14:54:35 (3.69 MB/s) - written to stdout [1476206212]

(base) [eolondela@ln008 DB_and_tools]$ mv profiles ${DATABASE_DIRECTORY}/Annotate/KOFAM/
(base) [eolondela@ln008 DB_and_tools]$ 
(base) [eolondela@ln008 DB_and_tools]$ 
(base) [eolondela@ln008 DB_and_tools]$ 
(base) [eolondela@ln008 DB_and_tools]$ serialize_kofam_models.py -d $MY_SCRATCH/DB_and_tools/Annotate/KOFAM/ -k $MY_SCRATCH/DB_and_tools/Annotate/KOFAM/ko_list -b $MY_SCRATCH/DB_and_tools/Annotate/KOFAM/kofam_june2024.pkl.gz
Loading KOfam HMMs: 100%|██████████████████████████████████| 26727/26727 [00:10<00:00, 2559.31it/s]
------------------------
Number of missing KOfams: 26727
------------------------

```

Then I ran it: 

```
(base) [eolondela@ln008 testing_kofams]$ pykofamsearch.py -i 638154511.faa  -o output.tsv -b $MY_SCRATCH/DB_and_tools/Annotate/KOFAM/kofam_june2024.pkl.gz -p=10 
Loading serialized KOFAM database
Performing HMMSearch: 0it [00:00, ?it/s]
------------------------
Number of missing KOfams: 26727
------------------------
```

This is with `-d` which works

```
(base) [eolondela@ln008 testing_kofams]$ pykofamsearch.py -i 638154511.faa  -o output.tsv -d $MY_SC
RATCH/DB_and_tools/Annotate/KOFAM/ -p =10
usage: pykofamsearch.py -i <proteins.fasta> -o <output.tsv> -d 
pykofamsearch.py: error: argument -p/--n_jobs: invalid int value: '=10'
(base) [eolondela@ln008 testing_kofams]$ pykofamsearch.py -i 638154511.faa  -o output.tsv -d $MY_SCRATCH/DB_and_tools/Annotate/KOFAM/ -p=10
Loading HMMs: 100%|█████████████████████████████████████████| 26727/26727 [02:20<00:00, 190.31it/s]
Performing HMMSearch: 100%|████████████████████████████████| 26234/26234 [00:19<00:00, 1354.87it/s]
------------------------
Number of missing KOfams: 493
------------------------
```

And this is my serialized DB: 

```
(base) [eolondela@ln008 testing_kofams]$ ls -lht $MY_SCRATCH/DB_and_tools/Annotate/KOFAM/kofam_june2024.pkl.gz
-rw-rw-r-- 1 eolondela grp-org-sc-mds 1.1M Jul  8 15:09 /clusterfs/jgi/scratch/science/mds/eolondela//DB_and_tools/Annotate/KOFAM/kofam_june2024.pkl.gz
```

**Comment by jolespin** [comment]
I think I got it.  

Try this: 

```bash
serialize_kofam_models.py -d $MY_SCRATCH/DB_and_tools/Annotate/KOFAM/profiles/ -k $MY_SCRATCH/DB_and_tools/Annotate/KOFAM/ko_list -b $MY_SCRATCH/DB_and_tools/Annotate/KOFAM/kofam_june2024.pkl.gz
```

You need to give `-d` the path to the `$MY_SCRATCH/DB_and_tools/Annotate/KOFAM/profiles/` profiles directory not the parent directory. 

```
  -d PROFILES, --profiles PROFILES
                        path/to/kofam_profiles_database_directory/ .  [Command: `wget -v -c ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz -O - |  tar -xz`]
```

**Comment by ericolo** [comment]
Thanks it worked now ! 
I'm sorry that I haven't seen this on the help page, that was a quick fix ! 

One final question: what does the number of missing KOfams mean ? It's always at 493, even when creating the serialized DB, am I missing some profiles ?

**Comment by jolespin** [comment]
Glad it worked.  The missing KOfams are basically discrepancies between what's in the `ko_list` file and the HMMs under the `profiles/`.  Nothing to be concerned about but just logging since the info is available. If all are missing then that's another story haha.  I'll try to make an error that says if all the KOfam are missing then maybe the wrong directory is being used.

**Comment by ericolo** [comment]
Okay got it, thanks a lot !!
